# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  pkgs,
  modulesPath,
  system,
  vars,
  ...
}:
let
  nvidia610 = config.boot.kernelPackages.nvidiaPackages.mkDriver {
    version = "610.43.02";

    sha256_64bit = "sha256-MDSgVLtM33dS/43CclZMsQVROAS/9TU4lFkBsWyndGM=";
    sha256_aarch64 = "sha256-isWTnokUA/dzWocFBLalnk4+O5gSExVjs3dVpdYTU88=";
    openSha256 = "sha256-hP5NVZZ4vGsACHLmUDKq4uckpd/kn1GxCSYnnJfAuBs=";
    settingsSha256 = "sha256-0YAhufRgjDW+uR+kjaTb154fibpcDw8QowfrucoZsKE=";
    persistencedSha256 = "sha256-Whgv9X+v2fRhzliOl2LzltY9v1SxDafFfv3IUPqj/hk=";
  };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    kernelPackages = pkgs.linuxPackages_zen;
    kernelModules = [
      "nvidia"
      "nvidia_modeset"
      "nvidia_uvm"
      "nvidia_drm"
      "ntsync"
    ];
    blacklistedKernelModules = [
      "ath12k_pci"
      "ath12k"
    ];
    kernelParams = [
      "quiet"
      "splash"
      "acpi_enforce_resources=lax"
      "video=DP-1:2560x1440@144"
      "video=DP-2:1920x1080@144"
      "video=HDMI-A-1:1920x1080@60"
      "zswap.enabled=1"
      "zswap.compressor=lz4"
      "zswap.max_pool_percent=20"
      "zswap.shrinker_enabled=1"
      "pcie_aspm=off"
    ];
    extraModulePackages = [ ];
    loader = {
      timeout = 0;
      systemd-boot = {
        enable = true;
        configurationLimit = 20;
      };
      efi.canTouchEfiVariables = true;
    };
    initrd = {
      luks = {
        devices = {
          "rootfs" = {
            device = "/dev/disk/by-label/ROOT";
            preLVM = true;
            crypttabExtraOpts = [
              "fido2-device=auto"
              "token-timeout=30"
            ];
          };
          "swap" = {
            device = "/dev/disk/by-label/SWAP";
            preLVM = true;
            allowDiscards = true;
            crypttabExtraOpts = [ "keyfile-timeout=10s" ];
            keyFile = "/swap.key";
          };
        };
      };
      secrets = {
        "/swap.key" = "/etc/secrets/swap.key";
      };
      systemd.enable = true;
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "sd_mod"
      ];
      verbose = false;
    };
    resumeDevice = "/dev/disk/by-label/swap";
    plymouth = {
      enable = true;
      theme = "tech_b";
      themePackages = with pkgs; [
        (adi1090x-plymouth-themes.override {
          selected_themes = [ "tech_b" ];
        })
      ];
    };
    consoleLogLevel = 3;
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/rootfs";
      fsType = "xfs";
    };

    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };

    "/home/${vars.username}/games" = {
      device = "/dev/disk/by-label/GAMES";
      fsType = "ext4";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];

  hardware = {
    enableAllFirmware = true;

    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [ nvidia-vaapi-driver ]; # For additional packages if needed
    };

    nvidia = {
      modesetting.enable = true;
      open = true;
      powerManagement.enable = true;
      nvidiaSettings = true;
      #package = config.boot.kernelPackages.nvidiaPackages.stable;
      package = nvidia610.overrideAttrs (old: {
        postInstall = (if old.postInstall or null == null then "" else old.postInstall) + ''
          if [ -n "''${firmware:-}" ] && [ -d firmware ]; then
            install -Dm644 -t "$firmware/lib/firmware/nvidia/$version" firmware/*.bin
          fi
        '';
      });
    };
  };

  nixpkgs.hostPlatform = "${system}";
}
