# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  system,
  vars,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    kernelPackages = pkgs.linuxPackages_xanmod;
    kernelModules = [
      "nvidia"
      "nvidia_modeset"
      "nvidia_uvm"
      "nvidia_drm"
    ];
    blacklistedKernelModules = [
      "ath12k_pci"
      "ath12k"
    ];
    kernelParams = [
      "quiet"
      "splash"
      "acpi_enforce_resources=lax"
      "video=DP-1:2560x1440@144"
      "video=DP-2:1920x1080@144"
      "video=HDMI-A-1:1920x1080@60"
    ];
    extraModulePackages = with config.boot.kernelPackages; [ ];
    loader = {
      timeout = 0;
      systemd-boot = {
        enable = true;
        configurationLimit = 5;
      };
      efi = {
        canTouchEfiVariables = true;
      };
    };
    initrd = {
      luks = {
        devices = {
          "rootfs" = {
            device = "/dev/disk/by-label/ROOT";
          };
          "swap" = {
            device = "/dev/disk/by-label/SWAP";
            preLVM = true;
            allowDiscards = true;
            keyFile = null;
          };
        };
      };
      systemd = {
        enable = true;
      };
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "sd_mod"
      ];
      verbose = false;
    };
    resumeDevice = "/dev/disk/by-label/swap";
    plymouth = {
      enable = true;
      theme = "tech_b";
      themePackages = with pkgs; [
        (adi1090x-plymouth-themes.override {
          selected_themes = [ "tech_b" ];
        })
      ];
    };
    consoleLogLevel = 3;
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/rootfs";
      fsType = "xfs";
    };

    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };

    "/home/${vars.username}/games" = {
      device = "/dev/disk/by-label/GAMES";
      fsType = "ext4";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];

  hardware = {
    enableAllFirmware = true;
  };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "${system}";
}
