# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelParams = [
  "video=DP-1:2560x1440@144"
  "video=DP-2:1920x1080@144"
  "video=HDMI-A-2:1920x1080@60"
  "acpi_enforce_resources=lax"
  "acpi_backlight=native"
];
  boot.kernelPackages = pkgs.linuxPackages_xanmod;
  boot.kernelModules = [ "kvm-amd" "i2c-dev" "i2c-piix4" "it87" "k10temp" ];
  boot.loader.systemd-boot.enable = true;  
  boot.loader.efi.canTouchEfiVariables = true;
  boot.initrd.luks.devices."luks-13479742-2586-406b-9016-048d6937f0b7".device = "/dev/disk/by-uuid/13479741-2586-406b-9016-048d6937f0b7";
}
