{
  inputs,
  ...
}:
{
  imports = [
    inputs.self.modules.nixos.attic-client
    inputs.self.modules.nixos.editor
    inputs.self.modules.nixos.locale
    inputs.self.modules.nixos.nix-settings
    inputs.self.modules.nixos.overlays
    inputs.self.modules.nixos.security
    inputs.self.modules.nixos.sops-nix
    inputs.self.modules.nixos.tailscale
    inputs.self.modules.nixos.yubikey
    inputs.self.modules.nixos.containers-pentesting
    inputs.self.modules.nixos.containers-virtualisation
  ];
}
