keys:
    # github CI uses this one
  - &gibson_old age123ky3yqvs5ptt45e94uqxr0ayzpr5sa2mqld87zqy42rk2s8qpgs3ndegr
    # new key for Gibson host
  - &gibson_new age1wxu48lctw4cpd4l3zrmq5f8434nm9hnd42ll5t2uveshfhh09e9slfsxek
creation_rules:
  - path_regex: ^secrets/.*$
    age:
      - *gibson_old
      - *gibson_new
